name: Java CI with Maven

on:
  push:
    branches:
      - main  # Trigger on push to main branch (change if using a different branch)
  pull_request:
    branches:
      - main  # Trigger on pull request to main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu for the environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Check out the code in the repository

      - name: Set up JDK 11
        uses: actions/setup-java@v2  # Set up the Java environment
        with:
          java-version: '11'  # Specify Java 11
          distribution: 'adoptopenjdk'  # You can also use 'openjdk' or 'zulu', but 'adoptopenjdk' is a common choice

      - name: Build with Maven
        run: mvn clean install -DskipTests=true  # Compile and package the application, skipping tests for faster builds

      - name: Run tests
        run: mvn test  # Run the unit tests to ensure everything works correctly

      - name: Build Docker image (optional)
        run: |
          docker build -t my-springboot-app .
          docker tag my-springboot-app myusername/my-springboot-app:latest
        # Uncomment and modify if you want to build a Docker image for the application

      - name: Push Docker image to DockerHub (optional)
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push myusername/my-springboot-app:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        # Uncomment and modify if you want to push the Docker image to DockerHub

      - name: Deploy to Server (optional)
        run: |
          # Add any deployment steps here, for example using SSH or SCP to deploy your application
          echo "Deploying to production server"
        # Replace with your actual deployment script/commands if needed
